#!/usr/bin/perl -w
use strict;
my $file=shift;
my $pwd=shift;
my $name=shift;
open(IN,"< $file");
open(L0, "> $pwd/$name.flank.0_5.ins.bed");
open(L1, "> $pwd/$name.flank.0_10.ins.bed");
open(L2, "> $pwd/$name.flank.0_20.ins.bed");
open(L3, "> $pwd/$name.flank.0_30.ins.bed");
open(L4, "> $pwd/$name.flank.0_40.ins.bed");
open(L5, "> $pwd/$name.flank.0_50.ins.bed");
open(L6, "> $pwd/$name.flank.0_60.ins.bed");
open(L7, "> $pwd/$name.flank.0_70.ins.bed");
open(L8, "> $pwd/$name.flank.0_80.ins.bed");
open(L9, "> $pwd/$name.flank.0_90.ins.bed");
open(L10, "> $pwd/$name.flank.0_100.ins.bed");
open(L11, "> $pwd/$name.flank.0_110.ins.bed");
open(L12, "> $pwd/$name.flank.0_120.ins.bed");
open(L13, "> $pwd/$name.flank.0_130.ins.bed");
open(L14, "> $pwd/$name.flank.0_140.ins.bed");
open(L15, "> $pwd/$name.flank.0_150.ins.bed");
open(L16, "> $pwd/$name.flank.0_200.ins.bed");
open(L17, "> $pwd/$name.flank.0_250.ins.bed");
open(L18, "> $pwd/$name.flank.0_300.ins.bed");
open(L19, "> $pwd/$name.flank.0_350.ins.bed");
open(L20, "> $pwd/$name.flank.0_400.ins.bed");
open(L21, "> $pwd/$name.flank.0_450.ins.bed");
open(L22, "> $pwd/$name.flank.0_500.ins.bed");
open(O,"> $pwd/00.sort.bed.work.sh");
open(O1,"> $pwd/01.make.benchmark.vcf.sh");
while(<IN>){
	chomp;
	if(/^#/){
		next;
	}else{
			my @line=split(/\t/,$_);
	                my $right_breakpoint=$line[2]+1;
	                my $left_breakpoint=$line[2];
			my $left_5=$left_breakpoint-5;
	                my $left_10=$left_breakpoint-10;
	                my $left_20=$left_breakpoint-20;
                        my $left_30=$left_breakpoint-30;
                        my $left_40=$left_breakpoint-40;
			my $left_50=$left_breakpoint-50;
			my $left_60=$left_breakpoint-60;
                        my $left_70=$left_breakpoint-70;
                        my $left_80=$left_breakpoint-80;
                        my $left_90=$left_breakpoint-90;
                        my $left_100=$left_breakpoint-100;
                        my $left_110=$left_breakpoint-110;
                        my $left_120=$left_breakpoint-120;
                        my $left_130=$left_breakpoint-130;
                        my $left_140=$left_breakpoint-140;
                        my $left_150=$left_breakpoint-150;
                        my $left_200=$left_breakpoint-200;
                        my $left_250=$left_breakpoint-250;
                        my $left_300=$left_breakpoint-300;
                        my $left_350=$left_breakpoint-350;
                        my $left_400=$left_breakpoint-400;
                        my $left_450=$left_breakpoint-450;
                        my $left_500=$left_breakpoint-500;
                        my $right_5=$right_breakpoint+5;
                        my $right_10=$right_breakpoint+10;
                        my $right_20=$right_breakpoint+20;
                        my $right_30=$right_breakpoint+30;
                        my $right_40=$right_breakpoint+40;
                        my $right_50=$right_breakpoint+50;
                        my $right_60=$right_breakpoint+60;
                        my $right_70=$right_breakpoint+70;
                        my $right_80=$right_breakpoint+80;
                        my $right_90=$right_breakpoint+90;
                        my $right_100=$right_breakpoint+100;
                        my $right_110=$right_breakpoint+110;
                        my $right_120=$right_breakpoint+120;
                        my $right_130=$right_breakpoint+130;
                        my $right_140=$right_breakpoint+140;
                        my $right_150=$right_breakpoint+150;
                        my $right_200=$right_breakpoint+200;
                        my $right_250=$right_breakpoint+250;
                        my $right_300=$right_breakpoint+300;
                        my $right_350=$right_breakpoint+350;
                        my $right_400=$right_breakpoint+400;
                        my $right_450=$right_breakpoint+450;
                        my $right_500=$right_breakpoint+500;
                        print L0  "$line[0]\t$left_5\t$left_breakpoint\n";
                        print L0  "$line[0]\t$right_breakpoint\t$right_5\n";
                        print L1  "$line[0]\t$left_10\t$left_breakpoint\n";
                        print L1  "$line[0]\t$right_breakpoint\t$right_10\n";
                        print L2  "$line[0]\t$left_20\t$left_breakpoint\n";
                        print L2  "$line[0]\t$right_breakpoint\t$right_20\n";
                        print L3  "$line[0]\t$left_30\t$left_breakpoint\n";
                        print L3  "$line[0]\t$right_breakpoint\t$right_30\n";
                        print L4  "$line[0]\t$left_40\t$left_breakpoint\n";
                        print L4  "$line[0]\t$right_breakpoint\t$right_40\n";
                        print L5  "$line[0]\t$left_50\t$left_breakpoint\n";
                        print L5  "$line[0]\t$right_breakpoint\t$right_50\n";
                        print L6  "$line[0]\t$left_60\t$left_breakpoint\n";
                        print L6  "$line[0]\t$right_breakpoint\t$right_60\n";
                        print L7  "$line[0]\t$left_70\t$left_breakpoint\n";
                        print L7  "$line[0]\t$right_breakpoint\t$right_70\n";
                        print L8  "$line[0]\t$left_80\t$left_breakpoint\n";
                        print L8  "$line[0]\t$right_breakpoint\t$right_80\n";
                        print L9  "$line[0]\t$left_90\t$left_breakpoint\n";
                        print L9  "$line[0]\t$right_breakpoint\t$right_90\n";
                        print L10  "$line[0]\t$left_100\t$left_breakpoint\n";
                        print L10  "$line[0]\t$right_breakpoint\t$right_100\n";
                        print L11  "$line[0]\t$left_110\t$left_breakpoint\n";
                        print L11  "$line[0]\t$right_breakpoint\t$right_110\n";
                        print L12  "$line[0]\t$left_120\t$left_breakpoint\n";
                        print L12  "$line[0]\t$right_breakpoint\t$right_120\n";
                        print L13  "$line[0]\t$left_130\t$left_breakpoint\n";
                        print L13  "$line[0]\t$right_breakpoint\t$right_130\n";
                        print L14  "$line[0]\t$left_140\t$left_breakpoint\n";
                        print L14  "$line[0]\t$right_breakpoint\t$right_140\n";
                        print L15  "$line[0]\t$left_150\t$left_breakpoint\n";
                        print L15  "$line[0]\t$right_breakpoint\t$right_150\n";
                        print L16  "$line[0]\t$left_200\t$left_breakpoint\n";
                        print L16  "$line[0]\t$right_breakpoint\t$right_200\n";
                        print L17  "$line[0]\t$left_250\t$left_breakpoint\n";
                        print L17  "$line[0]\t$right_breakpoint\t$right_250\n";
                        print L18  "$line[0]\t$left_300\t$left_breakpoint\n";
                        print L18  "$line[0]\t$right_breakpoint\t$right_300\n";
                        print L19  "$line[0]\t$left_350\t$left_breakpoint\n";
                        print L19  "$line[0]\t$right_breakpoint\t$right_350\n";
                        print L20  "$line[0]\t$left_400\t$left_breakpoint\n";
                        print L20  "$line[0]\t$right_breakpoint\t$right_400\n";
                        print L21  "$line[0]\t$left_450\t$left_breakpoint\n";
                        print L21  "$line[0]\t$right_breakpoint\t$right_450\n";
                        print L22  "$line[0]\t$left_500\t$left_breakpoint\n";
                        print L22  "$line[0]\t$right_breakpoint\t$right_500\n";
		}	
}
close IN;
print O "bedtools sort -i $pwd/$name.flank.0_5.ins.bed > $pwd/$name.ChineseQuartet.germline.GRCh38.tier1.flank.0_5.ins.sort.bed \n";
print O "bedtools sort -i $pwd/$name.flank.0_10.ins.bed > $pwd/$name.ChineseQuartet.germline.GRCh38.tier1.flank.0_10.ins.sort.bed \n";
print O "bedtools sort -i $pwd/$name.flank.0_20.ins.bed > $pwd/$name.ChineseQuartet.germline.GRCh38.tier1.flank.0_20.ins.sort.bed \n";
print O "bedtools sort -i $pwd/$name.flank.0_30.ins.bed > $pwd/$name.ChineseQuartet.germline.GRCh38.tier1.flank.0_30.ins.sort.bed \n";
print O "bedtools sort -i $pwd/$name.flank.0_40.ins.bed > $pwd/$name.ChineseQuartet.germline.GRCh38.tier1.flank.0_40.ins.sort.bed \n";
print O "bedtools sort -i $pwd/$name.flank.0_50.ins.bed > $pwd/$name.ChineseQuartet.germline.GRCh38.tier1.flank.0_50.ins.sort.bed \n";
print O "bedtools sort -i $pwd/$name.flank.0_60.ins.bed > $pwd/$name.ChineseQuartet.germline.GRCh38.tier1.flank.0_60.ins.sort.bed \n";
print O "bedtools sort -i $pwd/$name.flank.0_70.ins.bed > $pwd/$name.ChineseQuartet.germline.GRCh38.tier1.flank.0_70.ins.sort.bed \n";
print O "bedtools sort -i $pwd/$name.flank.0_80.ins.bed > $pwd/$name.ChineseQuartet.germline.GRCh38.tier1.flank.0_80.ins.sort.bed \n";
print O "bedtools sort -i $pwd/$name.flank.0_90.ins.bed > $pwd/$name.ChineseQuartet.germline.GRCh38.tier1.flank.0_90.ins.sort.bed \n";
print O "bedtools sort -i $pwd/$name.flank.0_100.ins.bed > $pwd/$name.ChineseQuartet.germline.GRCh38.tier1.flank.0_100.ins.sort.bed \n";
print O "bedtools sort -i $pwd/$name.flank.0_110.ins.bed > $pwd/$name.ChineseQuartet.germline.GRCh38.tier1.flank.0_110.ins.sort.bed \n";
print O "bedtools sort -i $pwd/$name.flank.0_120.ins.bed > $pwd/$name.ChineseQuartet.germline.GRCh38.tier1.flank.0_120.ins.sort.bed \n";
print O "bedtools sort -i $pwd/$name.flank.0_130.ins.bed > $pwd/$name.ChineseQuartet.germline.GRCh38.tier1.flank.0_130.ins.sort.bed \n";
print O "bedtools sort -i $pwd/$name.flank.0_140.ins.bed > $pwd/$name.ChineseQuartet.germline.GRCh38.tier1.flank.0_140.ins.sort.bed \n";
print O "bedtools sort -i $pwd/$name.flank.0_150.ins.bed > $pwd/$name.ChineseQuartet.germline.GRCh38.tier1.flank.0_150.ins.sort.bed \n";
print O "bedtools sort -i $pwd/$name.flank.0_200.ins.bed > $pwd/$name.ChineseQuartet.germline.GRCh38.tier1.flank.0_200.ins.sort.bed \n";
print O "bedtools sort -i $pwd/$name.flank.0_250.ins.bed > $pwd/$name.ChineseQuartet.germline.GRCh38.tier1.flank.0_250.ins.sort.bed \n";
print O "bedtools sort -i $pwd/$name.flank.0_300.ins.bed > $pwd/$name.ChineseQuartet.germline.GRCh38.tier1.flank.0_300.ins.sort.bed \n";
print O "bedtools sort -i $pwd/$name.flank.0_350.ins.bed > $pwd/$name.ChineseQuartet.germline.GRCh38.tier1.flank.0_350.ins.sort.bed \n";
print O "bedtools sort -i $pwd/$name.flank.0_400.ins.bed > $pwd/$name.ChineseQuartet.germline.GRCh38.tier1.flank.0_400.ins.sort.bed \n";
print O "bedtools sort -i $pwd/$name.flank.0_450.ins.bed > $pwd/$name.ChineseQuartet.germline.GRCh38.tier1.flank.0_450.ins.sort.bed \n";
print O "bedtools sort -i $pwd/$name.flank.0_500.ins.bed > $pwd/$name.ChineseQuartet.germline.GRCh38.tier1.flank.0_500.ins.sort.bed \n";
print O "rm $pwd/$name.flank.0_5.ins.bed $pwd/$name.flank.0_10.ins.bed $pwd/$name.flank.0_20.ins.bed $pwd/$name.flank.0_30.ins.bed $pwd/$name.flank.0_40.ins.bed $pwd/$name.flank.0_50.ins.bed $pwd/$name.flank.0_60.ins.sort.bed $pwd/$name.flank.0_70.ins.sort.bed $pwd/$name.flank.0_80.ins.sort.bed $pwd/$name.flank.0_90.ins.sort.bed $pwd/$name.flank.0_100.ins.bed $pwd/$name.flank.0_110.ins.bed $pwd/$name.flank.0_120.ins.bed $pwd/$name.flank.0_130.ins.bed $pwd/$name.flank.0_140.ins.bed $pwd/$name.flank.0_150.ins.bed $pwd/$name.flank.0_200.ins.bed $pwd/$name.flank.0_250.ins.bed $pwd/$name.flank.0_300.ins.bed $pwd/$name.flank.0_350.ins.bed $pwd/$name.flank.0_400.ins.bed $pwd/$name.flank.0_450.ins.bed $pwd/$name.flank.0_500.ins.bed \n";

print O1 "bedtools intersect -a /data/home/nxdang/project/t2t_version_cpc/chineseQuartet/filter_benchmarks/02.SV_benchmark/00.SNV/final_manal_check/insertion.tier1.supp2.tier2.filter.High_confidence.supp2.vcf.gz -b $pwd/$name.ChineseQuartet.germline.GRCh38.tier1.flank.0_5.ins.sort.bed -header|bgzip > $pwd/$name.ChineseQuartet.germline.GRCh38.tier1.HRA_HiFi_ILM.NotInRepeat.flank.0_5.tier1.supp2.tier2.high_confidence.supp2.vcf.gz \n";
print O1 "bedtools intersect -a /data/home/nxdang/project/t2t_version_cpc/chineseQuartet/filter_benchmarks/02.SV_benchmark/00.SNV/final_manal_check/insertion.tier1.supp2.tier2.filter.High_confidence.supp2.vcf.gz -b $pwd/$name.ChineseQuartet.germline.GRCh38.tier1.flank.0_10.ins.sort.bed -header|bgzip > $pwd/$name.ChineseQuartet.germline.GRCh38.tier1.HRA_HiFi_ILM.NotInRepeat.flank.0_10.tier1.supp2.tier2.high_confidence.supp2.vcf.gz \n";
print O1 "bedtools intersect -a /data/home/nxdang/project/t2t_version_cpc/chineseQuartet/filter_benchmarks/02.SV_benchmark/00.SNV/final_manal_check/insertion.tier1.supp2.tier2.filter.High_confidence.supp2.vcf.gz -b $pwd/$name.ChineseQuartet.germline.GRCh38.tier1.flank.0_20.ins.sort.bed -header|bgzip > $pwd/$name.ChineseQuartet.germline.GRCh38.tier1.HRA_HiFi_ILM.NotInRepeat.flank.0_20.tier1.supp2.tier2.high_confidence.supp2.vcf.gz \n";
print O1 "bedtools intersect -a /data/home/nxdang/project/t2t_version_cpc/chineseQuartet/filter_benchmarks/02.SV_benchmark/00.SNV/final_manal_check/insertion.tier1.supp2.tier2.filter.High_confidence.supp2.vcf.gz -b $pwd/$name.ChineseQuartet.germline.GRCh38.tier1.flank.0_30.ins.sort.bed -header|bgzip > $pwd/$name.ChineseQuartet.germline.GRCh38.tier1.HRA_HiFi_ILM.NotInRepeat.flank.0_30.tier1.supp2.tier2.high_confidence.supp2.vcf.gz \n";
print O1 "bedtools intersect -a /data/home/nxdang/project/t2t_version_cpc/chineseQuartet/filter_benchmarks/02.SV_benchmark/00.SNV/final_manal_check/insertion.tier1.supp2.tier2.filter.High_confidence.supp2.vcf.gz -b $pwd/$name.ChineseQuartet.germline.GRCh38.tier1.flank.0_40.ins.sort.bed -header|bgzip > $pwd/$name.ChineseQuartet.germline.GRCh38.tier1.HRA_HiFi_ILM.NotInRepeat.flank.0_40.tier1.supp2.tier2.high_confidence.supp2.vcf.gz \n";
print O1 "bedtools intersect -a /data/home/nxdang/project/t2t_version_cpc/chineseQuartet/filter_benchmarks/02.SV_benchmark/00.SNV/final_manal_check/insertion.tier1.supp2.tier2.filter.High_confidence.supp2.vcf.gz -b $pwd/$name.ChineseQuartet.germline.GRCh38.tier1.flank.0_50.ins.sort.bed -header|bgzip > $pwd/$name.ChineseQuartet.germline.GRCh38.tier1.HRA_HiFi_ILM.NotInRepeat.flank.0_50.tier1.supp2.tier2.high_confidence.supp2.vcf.gz \n";
print O1 "bedtools intersect -a /data/home/nxdang/project/t2t_version_cpc/chineseQuartet/filter_benchmarks/02.SV_benchmark/00.SNV/final_manal_check/insertion.tier1.supp2.tier2.filter.High_confidence.supp2.vcf.gz -b $pwd/$name.ChineseQuartet.germline.GRCh38.tier1.flank.0_60.ins.sort.bed -header|bgzip > $pwd/$name.ChineseQuartet.germline.GRCh38.tier1.HRA_HiFi_ILM.NotInRepeat.flank.0_60.tier1.supp2.tier2.high_confidence.supp2.vcf.gz \n";
print O1 "bedtools intersect -a /data/home/nxdang/project/t2t_version_cpc/chineseQuartet/filter_benchmarks/02.SV_benchmark/00.SNV/final_manal_check/insertion.tier1.supp2.tier2.filter.High_confidence.supp2.vcf.gz -b $pwd/$name.ChineseQuartet.germline.GRCh38.tier1.flank.0_70.ins.sort.bed -header|bgzip > $pwd/$name.ChineseQuartet.germline.GRCh38.tier1.HRA_HiFi_ILM.NotInRepeat.flank.0_70.tier1.supp2.tier2.high_confidence.supp2.vcf.gz \n";
print O1 "bedtools intersect -a /data/home/nxdang/project/t2t_version_cpc/chineseQuartet/filter_benchmarks/02.SV_benchmark/00.SNV/final_manal_check/insertion.tier1.supp2.tier2.filter.High_confidence.supp2.vcf.gz -b $pwd/$name.ChineseQuartet.germline.GRCh38.tier1.flank.0_80.ins.sort.bed -header|bgzip > $pwd/$name.ChineseQuartet.germline.GRCh38.tier1.HRA_HiFi_ILM.NotInRepeat.flank.0_80.tier1.supp2.tier2.high_confidence.supp2.vcf.gz \n";
print O1 "bedtools intersect -a /data/home/nxdang/project/t2t_version_cpc/chineseQuartet/filter_benchmarks/02.SV_benchmark/00.SNV/final_manal_check/insertion.tier1.supp2.tier2.filter.High_confidence.supp2.vcf.gz -b $pwd/$name.ChineseQuartet.germline.GRCh38.tier1.flank.0_90.ins.sort.bed -header|bgzip > $pwd/$name.ChineseQuartet.germline.GRCh38.tier1.HRA_HiFi_ILM.NotInRepeat.flank.0_90.tier1.supp2.tier2.high_confidence.supp2.vcf.gz \n";
print O1 "bedtools intersect -a /data/home/nxdang/project/t2t_version_cpc/chineseQuartet/filter_benchmarks/02.SV_benchmark/00.SNV/final_manal_check/insertion.tier1.supp2.tier2.filter.High_confidence.supp2.vcf.gz -b $pwd/$name.ChineseQuartet.germline.GRCh38.tier1.flank.0_100.ins.sort.bed -header|bgzip > $pwd/$name.ChineseQuartet.germline.GRCh38.tier1.HRA_HiFi_ILM.NotInRepeat.flank.0_100.tier1.supp2.tier2.high_confidence.supp2.vcf.gz \n";
print O1 "bedtools intersect -a /data/home/nxdang/project/t2t_version_cpc/chineseQuartet/filter_benchmarks/02.SV_benchmark/00.SNV/final_manal_check/insertion.tier1.supp2.tier2.filter.High_confidence.supp2.vcf.gz -b $pwd/$name.ChineseQuartet.germline.GRCh38.tier1.flank.0_110.ins.sort.bed -header|bgzip > $pwd/$name.ChineseQuartet.germline.GRCh38.tier1.HRA_HiFi_ILM.NotInRepeat.flank.0_110.tier1.supp2.tier2.high_confidence.supp2.vcf.gz \n";
print O1 "bedtools intersect -a /data/home/nxdang/project/t2t_version_cpc/chineseQuartet/filter_benchmarks/02.SV_benchmark/00.SNV/final_manal_check/insertion.tier1.supp2.tier2.filter.High_confidence.supp2.vcf.gz -b $pwd/$name.ChineseQuartet.germline.GRCh38.tier1.flank.0_120.ins.sort.bed -header|bgzip > $pwd/$name.ChineseQuartet.germline.GRCh38.tier1.HRA_HiFi_ILM.NotInRepeat.flank.0_120.tier1.supp2.tier2.high_confidence.supp2.vcf.gz \n";
print O1 "bedtools intersect -a /data/home/nxdang/project/t2t_version_cpc/chineseQuartet/filter_benchmarks/02.SV_benchmark/00.SNV/final_manal_check/insertion.tier1.supp2.tier2.filter.High_confidence.supp2.vcf.gz -b $pwd/$name.ChineseQuartet.germline.GRCh38.tier1.flank.0_130.ins.sort.bed -header|bgzip > $pwd/$name.ChineseQuartet.germline.GRCh38.tier1.HRA_HiFi_ILM.NotInRepeat.flank.0_130.tier1.supp2.tier2.high_confidence.supp2.vcf.gz \n";
print O1 "bedtools intersect -a /data/home/nxdang/project/t2t_version_cpc/chineseQuartet/filter_benchmarks/02.SV_benchmark/00.SNV/final_manal_check/insertion.tier1.supp2.tier2.filter.High_confidence.supp2.vcf.gz -b $pwd/$name.ChineseQuartet.germline.GRCh38.tier1.flank.0_140.ins.sort.bed -header|bgzip > $pwd/$name.ChineseQuartet.germline.GRCh38.tier1.HRA_HiFi_ILM.NotInRepeat.flank.0_140.tier1.supp2.tier2.high_confidence.supp2.vcf.gz \n";
print O1 "bedtools intersect -a /data/home/nxdang/project/t2t_version_cpc/chineseQuartet/filter_benchmarks/02.SV_benchmark/00.SNV/final_manal_check/insertion.tier1.supp2.tier2.filter.High_confidence.supp2.vcf.gz -b $pwd/$name.ChineseQuartet.germline.GRCh38.tier1.flank.0_150.ins.sort.bed -header|bgzip > $pwd/$name.ChineseQuartet.germline.GRCh38.tier1.HRA_HiFi_ILM.NotInRepeat.flank.0_150.tier1.supp2.tier2.high_confidence.supp2.vcf.gz \n";
print O1 "bedtools intersect -a /data/home/nxdang/project/t2t_version_cpc/chineseQuartet/filter_benchmarks/02.SV_benchmark/00.SNV/final_manal_check/insertion.tier1.supp2.tier2.filter.High_confidence.supp2.vcf.gz -b $pwd/$name.ChineseQuartet.germline.GRCh38.tier1.flank.0_200.ins.sort.bed -header|bgzip > $pwd/$name.ChineseQuartet.germline.GRCh38.tier1.HRA_HiFi_ILM.NotInRepeat.flank.0_200.tier1.supp2.tier2.high_confidence.supp2.vcf.gz \n";
print O1 "bedtools intersect -a /data/home/nxdang/project/t2t_version_cpc/chineseQuartet/filter_benchmarks/02.SV_benchmark/00.SNV/final_manal_check/insertion.tier1.supp2.tier2.filter.High_confidence.supp2.vcf.gz -b $pwd/$name.ChineseQuartet.germline.GRCh38.tier1.flank.0_250.ins.sort.bed -header|bgzip > $pwd/$name.ChineseQuartet.germline.GRCh38.tier1.HRA_HiFi_ILM.NotInRepeat.flank.0_250.tier1.supp2.tier2.high_confidence.supp2.vcf.gz \n";
print O1 "bedtools intersect -a /data/home/nxdang/project/t2t_version_cpc/chineseQuartet/filter_benchmarks/02.SV_benchmark/00.SNV/final_manal_check/insertion.tier1.supp2.tier2.filter.High_confidence.supp2.vcf.gz -b $pwd/$name.ChineseQuartet.germline.GRCh38.tier1.flank.0_300.ins.sort.bed -header|bgzip > $pwd/$name.ChineseQuartet.germline.GRCh38.tier1.HRA_HiFi_ILM.NotInRepeat.flank.0_300.tier1.supp2.tier2.high_confidence.supp2.vcf.gz \n";
print O1 "bedtools intersect -a /data/home/nxdang/project/t2t_version_cpc/chineseQuartet/filter_benchmarks/02.SV_benchmark/00.SNV/final_manal_check/insertion.tier1.supp2.tier2.filter.High_confidence.supp2.vcf.gz -b $pwd/$name.ChineseQuartet.germline.GRCh38.tier1.flank.0_350.ins.sort.bed -header|bgzip > $pwd/$name.ChineseQuartet.germline.GRCh38.tier1.HRA_HiFi_ILM.NotInRepeat.flank.0_350.tier1.supp2.tier2.high_confidence.supp2.vcf.gz \n";
print O1 "bedtools intersect -a /data/home/nxdang/project/t2t_version_cpc/chineseQuartet/filter_benchmarks/02.SV_benchmark/00.SNV/final_manal_check/insertion.tier1.supp2.tier2.filter.High_confidence.supp2.vcf.gz -b $pwd/$name.ChineseQuartet.germline.GRCh38.tier1.flank.0_400.ins.sort.bed -header|bgzip > $pwd/$name.ChineseQuartet.germline.GRCh38.tier1.HRA_HiFi_ILM.NotInRepeat.flank.0_400.tier1.supp2.tier2.high_confidence.supp2.vcf.gz \n";
print O1 "bedtools intersect -a /data/home/nxdang/project/t2t_version_cpc/chineseQuartet/filter_benchmarks/02.SV_benchmark/00.SNV/final_manal_check/insertion.tier1.supp2.tier2.filter.High_confidence.supp2.vcf.gz -b $pwd/$name.ChineseQuartet.germline.GRCh38.tier1.flank.0_450.ins.sort.bed -header|bgzip > $pwd/$name.ChineseQuartet.germline.GRCh38.tier1.HRA_HiFi_ILM.NotInRepeat.flank.0_450.tier1.supp2.tier2.high_confidence.supp2.vcf.gz \n";
print O1 "bedtools intersect -a /data/home/nxdang/project/t2t_version_cpc/chineseQuartet/filter_benchmarks/02.SV_benchmark/00.SNV/final_manal_check/insertion.tier1.supp2.tier2.filter.High_confidence.supp2.vcf.gz -b $pwd/$name.ChineseQuartet.germline.GRCh38.tier1.flank.0_500.ins.sort.bed -header|bgzip > $pwd/$name.ChineseQuartet.germline.GRCh38.tier1.HRA_HiFi_ILM.NotInRepeat.flank.0_500.tier1.supp2.tier2.high_confidence.supp2.vcf.gz \n";

		
